WARNING 2023-07-22 16:31:26,726 log log.py 241 log_response Method Not Allowed: /cronjob/api/server-info/
WARNING 2023-07-22 16:34:15,591 log log.py 241 log_response Method Not Allowed: /cronjob/api/server-info/
WARNING 2023-07-22 16:34:22,793 log log.py 241 log_response Method Not Allowed: /cronjob/api/server-info/
ERROR 2023-07-22 16:34:38,039 log log.py 241 log_response Internal Server Error: /cronjob/api/server-info/
Traceback (most recent call last):
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/CheckupApp/views.py", line 26, in server_info_list
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
                    ^^^^^^^^^^
NameError: name 'serializer' is not defined
WARNING 2023-07-22 16:36:01,088 log log.py 241 log_response Not Found: /cronjob/api/create_server_info
WARNING 2023-07-22 16:36:30,840 log log.py 241 log_response Method Not Allowed: /cronjob/api/create-server-info/
WARNING 2023-07-22 16:37:20,229 log log.py 241 log_response Method Not Allowed: /cronjob/api/create-server-info/
WARNING 2023-07-22 16:37:23,054 log log.py 241 log_response Method Not Allowed: /cronjob/api/create-server-info/
WARNING 2023-07-22 16:37:44,712 log log.py 241 log_response Method Not Allowed: /cronjob/api/create-server-info/
WARNING 2023-07-22 16:40:59,126 log log.py 241 log_response Bad Request: /cronjob/api/create-server-info/
WARNING 2023-07-22 16:46:25,082 log log.py 241 log_response Method Not Allowed: /cronjob/api/create-server-info/
ERROR 2023-07-22 16:46:29,165 log log.py 241 log_response Internal Server Error: /cronjob/api/create-server-info/
Traceback (most recent call last):
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/CheckupApp/views.py", line 25, in create_server_info
    return Response(serializer.data, status=status.HTTP_201_CREATED)
                    ^^^^^^^^^^
NameError: name 'serializer' is not defined
WARNING 2023-07-22 16:48:24,004 log log.py 241 log_response Method Not Allowed: /cronjob/api/create-server-info/
ERROR 2023-07-22 16:48:40,467 log log.py 241 log_response Internal Server Error: /cronjob/api/create-server-info/
Traceback (most recent call last):
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/CheckupApp/views.py", line 25, in create_server_info
    return Response(serializer, status=status.HTTP_201_CREATED)
                    ^^^^^^^^^^
NameError: name 'serializer' is not defined
WARNING 2023-07-22 16:49:56,373 log log.py 241 log_response Method Not Allowed: /cronjob/api/create-server-info/
ERROR 2023-07-22 16:50:19,734 log log.py 241 log_response Internal Server Error: /cronjob/api/create-server-info/
Traceback (most recent call last):
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/CheckupApp/views.py", line 25, in create_server_info
    return Response(serializer.data, status=status.HTTP_201_CREATED)
                                            ^^^^^^
NameError: name 'status' is not defined
WARNING 2023-07-22 16:51:08,403 log log.py 241 log_response Method Not Allowed: /cronjob/api/create-server-info/
ERROR 2023-07-22 17:04:14,388 log log.py 241 log_response Internal Server Error: /cronjob/api/server_up_down_check
Traceback (most recent call last):
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/myenv/lib64/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/html/serverHealthCheck/CheckupApp/views.py", line 146, in server_up_down_check
    "response_time_ms": response_time +"ms",
                        ~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'float' and 'str'
